version: '3'

services:
  react-ts:
    container_name: udemy-react-youtube-ts
    tty: true
    build:
        context: .
        dockerfile: Dockerfile.ReactTs
    volumes:
        - ./client/:/usr/src/app
    # command: sh -c "cd react-basic && yarn start"
    ports:
      - "3000:3000"
    tty: true

  django:
    container_name: udemy-youtube-django
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.Django
    environment:
        DJANGO_MODWSGI_EXTRA_ARGS: ""
        ALLOWED_HOSTS: '*'
        DATABASE_ENGINE: django.db.backends.postgresql
        DATABASE_DB: django_db
        DATABASE_USER: admin
        DATABASE_PASSWORD: admin
        DATABASE_HOST: udmey-youtube-postgres
        DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./server/:/code
    depends_on:
      - db

  db:
    image: postgres:11.4-alpine
    container_name: udmey-youtube-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

# # トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data: